### ISSUE TITLE
Readme 

### ISSUE THREAD

**Issue by arademaker** [LFG-PTBR/MorphoBr#10]
https://github.com/LFG-PTBR/MorphoBr/blob/master/diminutives/README.org

@leoalenc  , you are talking about Foma and xfst but only the last one was used , right ?

**Comment by odanoburu** [comment]
I think he used FOMA to create the diminutives!

**Comment by leoalenc** [comment]
@odanoburu @arademaker  I used FOMA to create the pairs,  because the non-commercial version of XFST  doesn't allow the generation from large transducers.  But I've tested the  compilation of the transducers with XFST because I need a  transducer in binary  format created with this tool for morphological analysis with XLE.  The good news is that my lexc grammar and the script used for compiling the alternation rules run successfully in both packages.

**Comment by arademaker** [comment]
Acho que não está claro ainda para mim o que foi a etapa de 'criação dos pares' (com o FOMA, que vc chamou também de _generation from large transducers_) e a etapa de compilação do transducer com o XFST.  Imagino que os pares são a entrada, produzida a partir do recurso, a partir deles é criado o transduzer em outra representação que finalmente pode ser compilada, é isso?

Obviamente ainda temos que entender ainda o que são as _lexc grammar_ e as _alternation rules_! ;-)

**Comment by leoalenc** [comment]
@arademaker veja primeira parte desse tutorial, que trata de transdutores sem pesos:

http://clt.gu.se/sites/clt.gu.se/files/mkp/clttutorial.pdf

Neste artigo eu explico outras noções importantes, como a redução de complexidade de máquinas de estados finitos por meio da geração de pares e recompilação das máquinas: 
https://link.springer.com/chapter/10.1007/978-3-319-09761-9_6

 Os pares consistem de duplas  onde o primeiro elemento é uma palavra flexionada e o segundo elemento é uma sequência de etiquetas, sendo a primeira etiqueta o lema da palavra, e as demais etiquetas codificam as propriedades morfossintáticas.  Enfim, o formato que nós estamos utilizando para os dicionários.

**Comment by leoalenc** [comment]
@arademaker  O XLE precisa  na análise morfológica de máquinas de estados finitos no formato binário gerado pelo XFST.  Isso não é uma limitação porque uma máquina de estados finitos compilada pelo foma pode ser convertida numa máquina no formato binário do XFST.  Portanto, na prática, o que é produzido no foma acaba podendo ser utilizado no XLE.
