### ISSUE TITLE
merging Label-Lex and DELAF-PB

### ISSUE THREAD

**Issue by arademaker** [LFG-PTBR/MorphoBr#18]
O dicionário PT do Freeling (https://github.com/TALP-UPC/FreeLing/tree/master/data/pt/dictionary) veio do http://label.ist.utl.pt/pt/labellex_pt.php. Algumas adaptações do Label-Lex foram feitas par compatibilização do dicionários com os módulos de processamento do Freeling. Possíveis artigos relevantes:

1. Gamallo, Pablo, and Marcos Garcia, ‘FreeLing E TreeTagger: Um Estudo Comparativo No Âmbito Do Português’, Gramatica.Usc.Es <http://gramatica.usc.es/~gamallo/artigos-web/PROLNAT_Report_01.pdf> [accessed 4 September 2015]
2. Garcia, Marcos, and Pablo Gamallo, ‘Análise Morfossintáctica Para Português Europeu E Galego: Problemas, Soluções E Avaliação’, 2010, 1–9
3. Garcia, Marcos, and Pablo Gamallo, ‘Using Morphosyntactic Post-Processing to Improve POS-Tagging Accuracy’, Inf.Pucrs.Br <https://www.inf.pucrs.br/~propor2010/proceedings/regular_papers/GarciaGamallo.pdf> [accessed 1 September 2015]
4. Garcia, Marcos, Pablo Gamallo, Iria Gayo, and Miguel A Pousada Cruz, ‘PoS-Tagging the Web in Portuguese. National Varieties, Text Typologies and Spelling Systems’, Procesamiento Del Lenguaje Natural, 53 (2014), 95–101
5. González, Marcos Garcia, ‘Extração De Relações Semânticas. Recursos, Ferramentas E Estratégias’, 2014, pp. 1–204
6. Eleutério, Samuel; E. M. Ranchhod; C. Mota; P. Carvalho, «Dicionários Electrónicos do Português. Características e Aplicações». In Actas do VIII Simposio Internacional de Comunicación Social, pp. 636-642, Centro de Lingüística Aplicada, Santiago de Cuba.

O MorphoBr veio de http://www.nilc.icmc.usp.br/nilc/projects/unitex-pb/web/dicionarios.html.  

Este issue trata do esforço de unir os dois recursos compatibilizando decisões tomadas pelos diferentes recursos.

**Comment by arademaker** [comment]
Seguindo sugestão do @leoalenc precisamos revisar lo código de conversão do Label-Lex/Freeling https://github.com/LFG-PTBR/MorphoBr/pull/11#issuecomment-380861475.

**Comment by odanoburu** [comment]
o que tem de ser feito nessa issue? ou ela fechou junto com #20 ?

**Comment by arademaker** [comment]
Acho que podemos fechar junto. Aqui estava pensando em algo que voltassemos a verificar a origem dos dados do Freeling mas agora já não acho que vale a pena.
