### ISSUE TITLE
merging Marcos Garcia Dic

### ISSUE THREAD

**Issue by arademaker** [LFG-PTBR/MorphoBr#20]
> O dicionário por defeito de FreeLing só contém formas de Português Europeu; este contém de PE, de PB e também novas formas do Acordo Ortográfico. Fizemos umas avaliações (o artigo ainda não está publicado), e o novo dicionário não é muito relevante para o PoS-tagging (salvo alguma palavrinha nova do Acordo), mas talvez sim para lematização de PB. Ora, como o processo de conversão e fusão foi quase tudo automático, também pode gerar dispersão e piorar os resultados :?

@leoalenc disse:

> Seria interessante comparar esse outro dicionário com aquele de São Carlos que nós já estamos usando. Poderemos extrair, por exemplo, aleatoriamente 20 formas de cada classe gramatical aberta que estão nesse novo dicionário mas não estão no de São Carlos.

> Seria interessante também comparar os lemas das classes abertas nos dois recursos, Produzindo duas listas com as diferenças. 

> Chamo atenção para a necessidade de levar em conta aquelas formas verbais faltantes no dicionário de São Carlos que eu criei. São formas do pretérito imperfeito e mais que perfeito da primeira e terceira pessoa do singular de verbos com pronomes, conforme apontei na questão número oito.

Estas formas faltantes que vc produziu já estão incorporadas nos arquivos? Como obte-las?

> Algumas pistas para fazer a comparação do língua livre com esse recurso do Marcos: como os dois recursos tratam os substantivos e adjetivos de gênero comum? Estou falando de palavras como dentista e alegre que não variam para gênero. Por conta disso, por exemplo o dicionário de São Carlos tende a ter mais formas, Uma vez que não trabalha com a noção de gênero comum nem de número comum (Palavras como simples e lápis).

Boa observação, como vamos compatibilizar isso? Vamos seguir São Carlos ou adotamos a postura mais compacta? Boa info para o artigo. Hoje temos no MorphoBr:

```
$ egrep "^dentista" nouns/*
nouns/d-i.dict:dentista	dentista+N+F+SG
nouns/d-i.dict:dentista	dentista+N+M+SG
nouns/d-i.dict:dentistas	dentista+N+F+PL
nouns/d-i.dict:dentistas	dentista+N+M+PL
```

Marcos e Freeling:

```
$ egrep "^dentista" tmp/marcos/dicc-AO3_long.src
dentista dentista NCCS000
dentistas dentista NCCP000
```

> A propósito: só pra facilitar o meu trabalho, você poderia colocar tanto o arquivo do língua livre quanto o dicionário do Marcos num ramo "experimental" do nosso repositório?

Vide ffe2e5d no ramo 'garcia'

**Comment by leoalenc** [comment]
@odanoburu @arademaker  as formas faltantes que eu gerei estão na pasta verbos e na pasta  verbos/clíticos, nos arquivos IQ3s.pairs e IQ1s.pairs. Corrigindo o que eu escrevi anteriormente, tantos verbos sem pronome quantos verbos com pronome apresentam essas lacunas.

**Comment by arademaker** [comment]
No branch master, só temos o `verbs/IQ3s.pairs`. Então os demais devem estar no branch `expansion`, certo?

**Comment by leoalenc** [comment]
@odanoburu @arademaker  eu sei que a versão do língua livre é mais econômica, mas, no estágio atual, quando nós temos muitas tarefas pendentes, eu não consideraria a conversão para o formato mais econômico uma prioridade. O programa de conversão entre os dois formatos elaborado na linguagem de programação GF trabalha com o formato mais redundante atualmente. Não existe consenso na linguística computacional  e na linguística teórica a respeito dessa  questão.   Além disso, a minha gramática léxico-funcional trabalha com o sistema mais redundante atualmente. Eu teria que mudar algumas coisas pra operar com o sistema mais  econômico.  Por fim, ressalto que precisaríamos definir etiquetas únicas para cada caso por exemplo MF para palavras que são masculinas e femininas.  Isso não me parece muito elegante, pelo menos agora.  Por tudo isso, proponho que continuemos a utilizar o sistema de São Carlos.

**Comment by leoalenc** [comment]
@arademaker  veja a pasta verbs/clitics/IQ1s.pairs

**Comment by leoalenc** [comment]
@arademaker  eu fiz a fusão  do ramo expansão, mas eu esqueci de fazer o push.  Problema resolvido.

**Comment by odanoburu** [comment]
> eu sei que a versão do língua livre é mais econômica, mas, no estágio atual, quando nós temos muitas tarefas pendentes, eu não consideraria a conversão para o formato mais econômico uma prioridade.

de fato não é! eu ainda tenho dúvidas sobre qual o melhor caminho (vejo vantagens e desvantagens nas duas escolhas), mas não é nada que deva ser resolvido agora.

só queria registrar aqui o que falei pessoalmente: a conversão por GF faz

    freeling -> delaf

sem problemas, mas o contrário não é feito corretamente para alguns inputs, justamente por causa das tags comuns/econômicas. GF não dispõe dos mecanismos de uma linguagem turing-completa para armazenar o fato de que a mesma forma apareceu duas vezes, uma com tag masculina e outra feminina, e que então deve-se retornar no formato freeling uma linha só com a tag `C`. assim, temos uma forma comum em freeling gerando duas linhas no delaf, mas duas linhas no delaf gerando as mesmas duas linhas no freeling.

**Comment by arademaker** [comment]
Converti o arquivo do Marcos Garcia para 1 tripla por linha `(form,lema,tags)`:

```

(with-open-file (fo "/Users/ar/work/MorphoBr/tmp/dicc-AO3_long-1pl.src"
		    :direction :output :if-exists :supersede)
  (with-open-file (fi "/Users/ar/work/MorphoBr/tmp/dicc-AO3_long.src")
    (do ((line (read-line fi nil nil)
	       (read-line fi nil nil)))
	((null line))
      (let ((reg (cl-ppcre:split "[ ]+" line)))
	(dotimes (i (/ (1- (length reg)) 2))
	  (format fo "~a ~a ~a~%" (car reg) (nth (+ 1 (* i 2)) reg) (nth (+ 2 (* i 2)) reg)))))))
```

depois 

```
$ cat freeling dicc-AO3_long-1pl.src | sort | uniq > fl+garcia-uniq.src
$ wc -l freeling dicc-AO3_long-1pl.src fl+garcia-uniq.src
 1214093 freeling
 1693140 dicc-AO3_long-1pl.src
 1815998 fl+garcia-uniq.src
 4723231 total
```

Logo temos efetivamente 600K formas a mais do Garcia adicionadas ao dicionário atual do Freeling.

**Comment by arademaker** [comment]
No arquivo `garcia+freeling.uniq.src` temos agora uma coluna extra com info do arquivo de origem. Podemos agora ver facilmente o que veio do Freeling e o que foi adicionado pelo Marcos.

**Comment by arademaker** [comment]
alguns bugs na unificação para resolver:

```
último último AO0MS0
último último AO0MS00
```

parece que Marcos colocou um zero a menos na tag dos adjetivos.

**Comment by odanoburu** [comment]
ele também mencionou tags diferentes no email, certo?

em geral as duas últimas tags são zero: 



Position | Atribute | Values
-- | -- | --
5 | possessorpers | 1:1; 2:2; 3:3
6 | possessornum | S:singular; P:plural; N:invariable

**Comment by arademaker** [comment]
No marcos+freeling, meio inconsistente né? Imagino que se ficarmos olhando para estes dados, não vamos parar de encontrar inconsistências...

```
mulher mulher NCFS000
mulher-aranha homem-aranha NCFS000
```

**Comment by arademaker** [comment]
Refazendo a conta de https://github.com/LFG-PTBR/MorphoBr/issues/20#issuecomment-381946906, temos 481K formas adicionais em relação ao freeling e 495K formas adicionais em relação ao dicionário do Marcos, os dois recursos se completaram bastante...

**Comment by odanoburu** [comment]
> alguns bugs na unificação para resolver:
```
último último AO0MS0
último último AO0MS00
```
vc resolveu isso, @arademaker ? não achei caso algum no `garcia+freeling.uniq.src`

**Comment by odanoburu** [comment]
> mulher-aranha homem-aranha NCFS000

isso é hilário!

**Comment by arademaker** [comment]
Sim, resolvi os casos de `AO0MS0 ~> AO0MS00`, vide `garcia+freeling.sh`.

**Comment by odanoburu** [comment]
:+1:

**Comment by odanoburu** [comment]
estou colocando os arquivos freeling+garcia (GFL) nos diretórios das classes, com a extensão `diff.gfl`, indicando que são só as linhas não encontradas já no MorphoBR.

passo-a-passo da união (vai para um README quando eu terminar):
```sh
# coloca prefixo de origem nos arquivos
sed -e 's/^/delaf\t/' adverbs.dict > adverbs.delaf
sed -e 's/^/gfl\t/' adv.gfl.dict > adverbs.gfl
# junta no mesmo arquivo
# notar que o .delaf vem antes, para que as duplicatas sejam eliminadas no .gfl
cat adverbs.delaf adverbs.gfl > adverbs.all
# sort e remove duplicatas, considerando só os campos a partir do primeiro TAB (i.e. ignora o prefixo)
sort -u -k2 adverbs.all > adverbs.uniq
# pega as linhas que sobraram do GFL
grep -P "gfl\t" adverbs.uniq > adverbs.diff.gfl
```
eu rodei esses comandos com vários `wc -l` in-between, para checar se estava tudo certo.
