### ISSUE TITLE
DELAF-PB lacks SBJF 3 SG of vender

### ISSUE THREAD

**Issue by leoalenc** [LFG-PTBR/MorphoBr#21]
@odanoburu @arademaker Essa lacuna atinge a maioria dos verbos da segunda conjugação. Pelas minhas contas, 72 verbos  dessa conjugação possuem a terceira pessoa do singular do futuro do subjuntivo. Para primeira pessoa, no entanto, são 800 formas.

**Comment by arademaker** [comment]
Como resolver este problema? Vc irá tratar isso gerando estas formas?  Ao juntar os recursos alguns destes casos podem aparecer vindos do Freeling ou Marcos.

**Comment by leoalenc** [comment]
@arademaker  a solução nesse caso  é trivial , a mesma que eu adotei para as formas do imperfeito e do mais que perfeito dos verbos da primeira conjugação, uma simples pipe de grep e sed,  Como está no arquivo sobre as formas faltantes da pasta verbos.

**Comment by leoalenc** [comment]
@odanoburu @arademaker   Problema resolvido para essa lacuna específica. É preciso remover as duplicatas quando o arquivo que comitei for unido com o arquivo geral de verbos.  Ou seja, eu criei as formas de terceira pessoa do  singular do futuro do subjuntivo para todos os verbos da segunda conjugação, mas 72 desses verbos já possuíam essa forma, Conforme o meu primeiro comentário.

**Comment by arademaker** [comment]
@leoalenc não claro para mim ainda, desculpe. sim, usando sed+grep porque estas novas formas são iguais ou facilmente derivadas a outras formas já existentes? é isso? Talvez se vc copiar/colar o script em um comentário, fica mais claro.

**Comment by arademaker** [comment]
Depois disso, podemos fechar este issue então?

**Comment by leoalenc** [comment]
@arademaker  sim, em todos os três casos, trata-se de formas idênticas. É um fenômeno generalizado no português, em muitos tempos a primeira pessoa do singular é idêntica à  terceira pessoa do singular. 
grep -Eh ".*er\+V\+SBJF\+1\+SG" x*.pairs | sed "s@1@3@g" > er-verbs-SBJF3SG.pairs
