### ISSUE TITLE
Superlative in adjectives incorrectly tagged

### ISSUE THREAD

**Issue by leoalenc** [LFG-PTBR/MorphoBr#39]
@odanoburu  O superlativo de adjetivos está incorretamente etiquetado como SBJR, etiqueta destinada ao subjuntivo presente.  A razão desse erro está na minha tabela de conversão, onde aparecem duas vezes a letra S.  Quando o dicionário na linguagem piton é construído, o valor SUPER, atribuído inicialmente à chave S, é sobrescrito como SBJR.  O que me induziu a esse erro foi o fato de que a letra S tem dois valores no dicionário de São Carlos,  superlativo dos adjetivos e subjuntivo presente dos verbos!  Vou corrigir manualmente via SED esse erro nos arquivos dos adjetivos!

**Comment by leoalenc** [comment]
@odanoburu @arademaker   A questão  que eu coloco pra vocês é esta: será que esse erro não repercutiu nos processos que vocês desenvolveram?  Eu já corrigi os arquivos afetados que eu criei.

**Comment by odanoburu** [comment]
a quais processos vc se refere, @leoalenc? se buscarmos por adjetivos com etiqueta SBJR poder'iamos tirar teima, certo?

**Comment by leoalenc** [comment]
@odanoburu @arademaker  eu me refiro a qualquer tipo de comando ou programas que vocês tenham executado pelos quais esse bug pode ter se propagado. Da minha parte já sanei os danos via SED.  Você pode por precaução executar  de novo essa sugestão sua.

**Comment by odanoburu** [comment]
@leoalenc ah sim! esse erro está só no DELAF, certo? se sim, acho que nada que fiz deve ter sido afetado não.

será que o experimento do corpus precisa ser re-rodado? @fcbr

**Comment by odanoburu** [comment]
acho que podemos fechar essa issue, certo?

**Comment by arademaker** [comment]
Mas o problema identificado foi corrigido ? Qual commit ?

**Comment by odanoburu** [comment]
o Leonel marcou o commit, está na linha do tempo da issue: https://github.com/LFG-PTBR/MorphoBr/commit/54f31b208b24af19b0de5c46626097fd8ec9bd54
