### ISSUE TITLE
clitic tagset

### ISSUE THREAD

**Issue by odanoburu** [LFG-PTBR/MorphoBr#4]
se `AD` === `accusative or dative`, pq não dar um tratamento semelhante à ambiguidade?

e.g.:
```
nos    ACC.3.M.PL/AD.1.PL
```
ficaria como
```
nos    ACC.3.M.PL/ACC.1.PL/DAT.1.PL
```

**Comment by leoalenc** [comment]
Boa questão é essa que você coloca! Mas O caso do "nos" É diferente do que ocorre com os pronomes "me", "te" e "vos".  Nesses últimos casos, eu tenho uma neutralização da oposição entre acusativo e dativo,  que eu estou marcando com a etiqueta AD. No caso do "nos", porém, eu tenho uma ambiguidade entre um pronome de primeira pessoa dO plural  E um pronome de terceira pessoa do plural, o "os" que vira "nos" depois de nasal. Se adotássemos a solução que você propõe,  eliminando a etiqueta AD, ganharíamos  quatro formas a mais para cada verbo!  Minha solução, portanto, permite a redução do tamanho do dicionário. Você concorda?  essa minha estratégia vai de encontro ao que foi adotado no dicionário original, ela poderia ser adotada em muitos outros casos, permitindo uma grande redução de tamanho.  Mas eu acho que agora não teremos tempo para implementar todas essas mudanças.

**Comment by arademaker** [comment]
Era o que suspeitava ,antiguidade vs neutralidade . Obrigado pela explicação
