### ISSUE TITLE
DELAF inconsistency?

### ISSUE THREAD

**Issue by odanoburu** [LFG-PTBR/MorphoBr#43]
para a consistência da anotação do DELAF, em que uma entrada como `dentista` tem duas linhas (uma para cada gênero), a entrada abaixo tb deveria ser quebrada em duas, correto? estou abrindo a issue para saber se não herdamos esse problema. 

```
abstrair,abstrair.V:W31
->
abstrair,abstrair.V:W3
abstrair,abstrair.V:W1
```

**Comment by leoalenc** [comment]
@odanoburu  você poderia me dizer qual seria a outra entrada?  De imediato,  só lendo seu comentário,  sem manipular os dados do dicionário, não consegui descobrir o que está faltando.

**Comment by odanoburu** [comment]
@leoalenc está mais claro agora, @leoalenc ??
