### ISSUE TITLE
tagset inconsistency?

### ISSUE THREAD

**Issue by odanoburu** [LFG-PTBR/MorphoBr#49]
@leoalenc, uma dúvida sobre essa parte do tagset dos cliticos:

> - A feature is not specified when it is not explicitly.
  marked, e.g. "lhe", "me", etc. are not marked for gender. In this
  respect, compare these forms, for example, with "a" and "o".

não seria mais consistente com as outras escolhas se gerássemos uma entrada com cada gênero? ou é semelhante à #4?

**Comment by leoalenc** [comment]
@odanoburu É  a mesma coisa que no caso de "nos".  Na língua portuguesa, apenas os pronomes de terceira pessoa têm marca de gênero.  Considero um dos erros mais graves do dicionário de São Carlos apresentar várias entradas, Uma para cada gênero,  para pronomes como eu, tu e você. É uma situação completamente diferente do que nós temos no caso dos adjetivos, Que em grande número se flexionam para gênero.  Se fosse para uniformizar, eu recomendaria não especificar o gênero de adjetivos como feliz.   mas  a eliminação de etiquetas de gênero no caso de palavras como feliz  é um dos tantos assuntos que nós podemos discutir no futuro, agora temos outras prioridades.

**Comment by leoalenc** [comment]
@odanoburu "lhe" é  terceira pessoa,  mas é um pronome dativo, abolindo a distinção de gênero.  Só para concluir, asseguro que não há nenhuma necessidade uma gramática computacional do português de fazer a especificação do gênero dessa palavra, porque ela não está em oposição de gênero com outra.

**Comment by odanoburu** [comment]
ok, saquei! obrigado!
