### ISSUE TITLE
Including tags for lemmas of clitic pronouns 

### ISSUE THREAD

**Issue by leoalenc** [LFG-PTBR/MorphoBr#5]
Constatei que, para a gramática léxico-funcional do português no sistema de desenvolvimento da xerox produzir análises em conformidade com as do projeto pargram, É preciso incluir, no mapeamento das propriedades dos clíticos,  os respectivos lemas ou formas canônicas.

**Comment by leoalenc** [comment]
Caso concordem, posso preparar uma nova versão dos arquivos com esses verbos.

**Comment by arademaker** [comment]
Ainda não consigo julgar pela sua descrição o que exatamente este esforço irá significar, e como e se poderíamos ajudar. Mas a cada dia estou entendendo mais e tem outras mensagens suas para ler. De qq forma, se vc consegue fazer concordamos

**Comment by odanoburu** [comment]
@leoalenc nós não podemos derivar a forma canônica da anotação das features? ou estou errado? 

na verdade acho que não entendi bem a situação, pois não entendi casos como esses:
```
ababada-lo	ababadar+V.ele.ACC.3.M.SG+PRS+2+SG
ababadamo-nos	ababadar+V.ele.ACC.3.M.PL+PRF+1+PL
ababadar-lhes-ás	ababadar+V.ele.DAT.3.PL+FUT+2+SG
```

**Comment by leoalenc** [comment]
A relação entre os traços e as formas canônicas é sistemática,  por exemplo -lo  É sempre acusativo, terceira pessoa, masculino e singular.   O inverso, porém, não se verifica: um pronome acusativo, terceira pessoa, masculino e singular pode ser também "o"  ou "no".  Isso depende de sufixo da forma flexionada.  O meu programa faz exatamente essa conversão, levando em conta o sufixo da forma flexionada e os traços, Que são os valores das chaves do dicionário de Python , ou seja, as formas dos pronomes .  No ambiente de desenvolvimento linguístico da xerox, não parece ser possível fazer  esse mapeamento.  Daí a necessidade de codificação explícita.  Por outro lado, como os clíticos estão desaparecendo da língua portuguesa do Brasil, muitos usuários não conseguirão  fazer o que o meu programa faz, porque Desconhecem as regras do português castiço, ainda usado em Portugal!  Por exemplo, eu duvido que mais de 1% da população brasileira saiba que o "nos" tem a ambiguidade que eu mostrei!

**Comment by leoalenc** [comment]
@odanoburu  O pronome acusativo recebe um ele no início quando a forma verbal termina em R ou s,  Como no primeiro caso que você mencionou .  Quando a terminação do verbo contém  ditongo nasal,  E somente nesses casos, o pronome acusativo recebe um N no início.  Desse modo, a segunda forma que você mencionou foi anotada de forma errada pelo meu programa! Você encontrou um bug!  Nesse caso, o pronome é apenas de segunda pessoa do plural! Vou corrigir  esse problema.  O terceiro caso que você mencionou está correto. O que você não entendeu exatamente?  A forma que vale a "lhes ababadarás".

**Comment by odanoburu** [comment]
hum, se entendi bem, conseguimos saber o lema/forma canônica de forma determinística. se é assim, acho que o dicionário fica menor/melhor sem os lemas, que podem ser colocados por um script como o seu para o processamento pelo XLE. inclusive podemos disponibilizá-lo no diretório `tools/`!

no terceiro caso me confundi, a análise faz sentido mesmo!

**Comment by leoalenc** [comment]
@odanoburu Eu ainda acho que a relação custo-benefício é favorável a especificar os lemas, existe até uma questão de elegância:  em muitos outros casos, podemos determinar a forma canônica a partir da forma flexionada, no entanto, essas formas são especificadas. Por que tratar os pronomes clíticos de forma diferente?   As mesmas formas quando são usadas separadas do verbo têm  seus lemas especificados! Do meu ponto  de vista, existem muitos problemas de design no recurso original.  Acho que vamos ganhar se nós corrigimos esses problemas. @arademaker O que acha?

**Comment by leoalenc** [comment]
@odanoburu @arademaker Se é pra reduzir o tamanho, eu recomendaria adotar outras estratégias, como não distinguir masculino e feminino quando isso não é marcado morfologicamente , por exemplo no caso de substantivos como dentista ou adjetivos como elegante, amável, entre centenas, senão milhares de outros casos. Existem também centenas, talvez milhares de substantivos que também funcionam como adjetivos e mesmo verbos!  Seria mais econômico usar tags compostas, como A-N ou A-N-V.  Enfim, se for pra derivar as coisas por meio de scripts,  É preciso ser consequente e aplicar  A estratégia nos outros casos. No entanto, sou cético em relação a essa estratégia,   Se a questão é reduzir o tamanho, basta compilar o recurso numa máquina de estados finitos, sem precisar fazer scripts.  O Usuário pode então gerar a lista de Pares a partir da máquina com um simples comando.

**Comment by odanoburu** [comment]
> em muitos outros casos, podemos determinar a forma canônica a partir da forma flexionada, no entanto, essas formas são especificadas. Por que tratar os pronomes clíticos de forma diferente?

concordo que não devemos tratar diferente! só estou tentando entender se isso se encaixa no tratamento das formas canônicas de, por exemplo, nomes, que muitas vezes (mas não sempre) podem ser inferidas, ou se se encaixa no tratamento de formas verbais "redundantes" (por assim dizer).

> Do meu ponto de vista, existem muitos problemas de design no recurso original. Acho que vamos ganhar se nós corrigimos esses problemas.

vamos conversar sobre isso então! mas melhor deixarmos mais ou menos como está até a entrega do artigo, certo?

**Comment by leoalenc** [comment]
Sim, minha proposta se encaixa no tratamento de todas as classes flexionáveis do delaf-PB. Estou apenas sendo consequente, seguindo a filosofia subjacente ao tratamento dessas classes.  Não podemos pegar esse recurso no seu valor de face, herdando suas falhas!

**Comment by leoalenc** [comment]
@odanoburu  mas concordo que devemos deixar o recurso no seu formato atual, ou seja, o que já temos agora no repositório, com as correções que eu já implementei. Falta eliminar apenas as duplicatas.  Isso vocês fazem quando mudarem o formato de distribuição.

**Comment by odanoburu** [comment]
esta issue est'a fechada ent'ao, @leoalenc ? (a n'ao ser, talvez, por remocao de duplicatas)?

**Comment by leoalenc** [comment]
@odanoburu  sim,  a questão da anotação  dos pronomes  incorporados aos verbos está completamente resolvida.

**Comment by leoalenc** [comment]
@odanoburu  basta verificar a questão das duplicatas.
