### ISSUE TITLE
duplicatas

### ISSUE THREAD

**Issue by odanoburu** [LFG-PTBR/MorphoBr#6]
há duplicatas em vários arquivos. 

se as duplicatas estão no mesmo arquivo, basta um `sort -u file > sorted-file`. 

se estão em arquivos diferentes, usando o comando `comm -1 -3 old new > new-new` podemos obter as linhas de new que não estão em old.

- [x] nouns
   - [x] diminutives
- [x] adjs
- [x] advs
- [x] verbs

**Comment by leoalenc** [comment]
Interessante! Precisamos mesmo eliminar as duplicatas. Alguém pode verificar se elas existem no dicionário original?

**Comment by arademaker** [comment]
O DELAF_PB Versão 2 (versão sem grafos de flexão):

```
$ wc -l Delaf2015v04.dic
 9072338 Delaf2015v04.dic
$ cat Delaf2015v04.dic | sort | uniq -c | wc -l
 8753655
```

Ou seja, temos 318.683 linhas repetidas.

**Comment by odanoburu** [comment]
muito estranho tantas repetições, não é mesmo? deve ter um motivo..

**Comment by arademaker** [comment]
Aqui são as primeiras linhas com mais de 1 ocorrência. @odanoburu imagino que se o processo de geração das flexões começou com um arquivo com algumas duplicatas, facilmente produziu estas 300K duplicatas finais.

```
$ cat Delaf2015v04.dic | sort | uniq -c | awk '$1 > 1' | head -100
   2 ababadam-nos,ababadar.V+PRO:P3p
   2 ababadar-lhe,ababadar.V+PRO:U3s
   2 ababadar-lhes,ababadar.V+PRO:U3s
   2 ababadar-me,ababadar.V+PRO:U3s
   2 ababadar-nos,ababadar.V+PRO:U3s
   2 ababadar-te,ababadar.V+PRO:U3s
   2 ababadar-vos,ababadar.V+PRO:U3s
   2 ababadaram-nos,ababadar.V+PRO:J3p
   2 ababadaram-nos,ababadar.V+PRO:Q3p
   2 ababadarem-nos,ababadar.V+PRO:U3p
   2 ababadarem-nos,ababadar.V+PRO:W3p
   2 ababadavam-nos,ababadar.V+PRO:I3p
   2 ababade,ababadar.V:S3s
   2 ababade,ababadar.V:Y3s
   2 ababade-a,ababadar.V+PRO:Y3s
```

**Comment by odanoburu** [comment]
que bom que o dicionário vai reduzir um pouco de tamanho então :)

**Comment by arademaker** [comment]
3% das linhas são repetições, mas sim já é uma redução.

**Comment by leoalenc** [comment]
@arademaker @odanoburu não há razão pras repetições, é bug do delaf-pb mesmo!

**Comment by odanoburu** [comment]
ok! vamos fechar a issue quando corrigirmos (acho mais fácil corrigir quando formos mudar o formato de distribuição).

**Comment by arademaker** [comment]
@odanoburu este issue já foi resolvido em recente PR certo?

**Comment by arademaker** [comment]
Temos agora nos arquivos de verbos ainda repetições. E certamente apenas depois de juntarmos Freeling e Marcos teremos o resultado final de duplicações. Acho que mesmo que mantivermos os dados que vieram de Freeling (indiretamente Label-Lex) e Marcos, devemos manter estes arquivos separados apenas com o que já não está no DELAF*

Mas sinceramente, estou achando que é mais fácil juntar. 

```
$ pwd
/Users/ar/work/MorphoBr/verbs
$ cat *.pairs > verbs.tudo
$ sort verbs.tudo | uniq -c | awk '$1 > 1 {print}' | wc -l
   23608
```

**Comment by arademaker** [comment]
@odanoburu falamos hoje sobre isso certo? Podemos considerar como sugerido pelo @leoalenc que o DELAF-PB é a fonte original prioritária. Nos diretórios de cada classe, ficarão arquivos com apenasos dados 'novos' que vieram de GFL (Garcia+Freeling).

**Comment by odanoburu** [comment]
sim ! da forma que fiz está ok, né? vou remover as duplicatas agora
