### ISSUE TITLE
missing plural of feminine nouns

### ISSUE THREAD

**Issue by leoalenc** [LFG-PTBR/MorphoBr#64]
The plural forms of the following feminine nouns  are missing:

```
~/MorphoBr$ grep -E "[[:space:]]pólio\+N" nouns/*.dict
nouns/j-p.delaf.dict:pólio      pólio+N+F+SG
nouns/j-p.delaf.dict:pólio      pólio+N+M+SG
nouns/j-p.delaf.dict:pólios     pólio+N+M+PL

~/MorphoBr$ grep -E "[[:space:]]ratio\+N" nouns/*.dict
nouns/nouns.gfl.dict:ratio      ratio+N+F+SG

~/MorphoBr$ grep -E "[[:space:]]expo\+N" nouns/*.dict
nouns/d-i.delaf.dict:expo       expo+N+F+SG
nouns/nouns.gfl.dict:expo       expo+N+M+SG
nouns/nouns.gfl.dict:expos      expo+N+M+PL
```

As for the last three entries, feminine noun  "expo" is derived from "exposição", which means "exposition" (Michaelis). It seems that masculine "expo" doesn't exist, at least it is not registered in Infopédia, Dicio, Priberam, Michaelis, and iAulete.

**Comment by vcvpaiva** [comment]
Mas Leonel polio  nao tem masculino! nao existe um polio??? polio nao 'e simplesmente abreviacao de poliomielite, UMA doenca?? e', nao estou entendendo.

**Comment by leoalenc** [comment]
@vcvpaiva, o dicionário Houaiss, entre outros, registra o substantivo masculino pólio, um tipo de erva. Quanto ao substantivo pólio no feminino, é forma reduzida da doença poliomielite, como você menciona. O erro atual do nosso recurso é não incluir o plural da forma feminina.

**Comment by arademaker** [comment]
Para ratio temos https://dicionario.priberam.org/ratio (s.m.). substantivo masculino. Temos evidência dela como feminino?

**Comment by arademaker** [comment]
para o significado de pólio como s.f. (doença), não consigo pensar em uma frase ...

**Comment by arademaker** [comment]
Google não tem retorno para “sarampos” como não tem para “polios”

**Comment by vcvpaiva** [comment]
Alexandre, "ratio" tem que ser feminino, pois e' a razao, ne? a taxa. 
e obrigada pela explicacao de polio erva, Leonel. 

As doencas associadas a poliomielite sao varias. As polios se distinguem por terem sintomas diferentes, de acordo com o tipo de origem blah blah.
[isso 'e completamente falso, eu nao tenho nunhuma ideia do que causa a polio, mas acho que mostra que polios existe e a palavra tem que ser feminina] meus dois centavos, 'e claro.

**Comment by arademaker** [comment]
dentre os dicionários que listamos no wiki, em https://www.dicio.com.br/ratio/, para mim parece uma palavra em EN cuja tradução seria 'proporção'. E https://dicionario.priberam.org/ratio como disse acima.

OK, obrigado pelo exemplo de `pólios`.

**Comment by arademaker** [comment]
para fechar este issue só falta decidirmos sobre `ratio`. Seria bom sempre argumentarmos com referencias... e continuarmos acrescentando nossas fontes no Wiki.

**Comment by leoalenc** [comment]
> Google não tem retorno para “sarampos” como não tem para “polios”

É “pólios” com acento agudo. Além do ótimo exemplo de @vcvpaiva, vejam:

http://www.portaldalinguaportuguesa.org/?action=lemma&lemma=39773

@arademaker, como já afirmei noutras ocasiões a propósito dos diminutivos, o léxico deve incluir tanto as palavras bem formadas existentes, ou seja, que se podem encontrar em corpora representativos, quanto as palavras potenciais, que se podem criar com base na gramática. Desse modo, todo substantivo deve ter forma de plural num recurso que se pretenda abrangente, mesmo que essa forma seja apenas potencial. Esse é o caso de “sarampo” e qualquer outro nome de doença, como reconhece este recurso português:

http://www.portaldalinguaportuguesa.org/index.php?action=lemma&lemma=33723

Num dado momento, pode existir apenas uma forma de uma dada doença, mas não se pode dizer de antemão que não surgirão subtipos no futuro. Um modelo do léxico deve contemplar essa possibilidade, assumindo um caráter preditivo, como o teve a tabela periódica quando foi criada (devo esse exemplo a um colega engenheiro e linguista da UFMA).

**Comment by leoalenc** [comment]
> para fechar este issue só falta decidirmos sobre `ratio`. Seria bom sempre argumentarmos com referencias... e continuarmos acrescentando nossas fontes no Wiki.

@arademaker, veja:

http://www.portaldalinguaportuguesa.org/index.php?action=lemma&lemma=128340

Mas existe também a forma feminina, termo técnico do direito, cujo plural precisamos incluir:

“ Uma ratio muito específica se aplicaria a caso futuro somente se este fosse absolutamente igual em suas circunstâncias fáticas.”

http://www.sbdp.org.br/arquivos/material/19_Estudo%20dirigido%20-%20Ratio%20decidendi%20e%20obter%20dictum%20-%20Conrado%20Hubner%20Mendes.pdf

**Comment by arademaker** [comment]
Último commit fecha este issue. Das discussões acima, resumo meu entendimento:

1. Para `polios` não apenas @vcvpaiva ajudou mostrando um possível uso do s.f.p mas @leoalenc bem lembrou que o recurso deve abranger as palavras potenciais e não apenas as palavras que encontradas em corpora. A comparação com a tabela periódica é interessante. Curiosamente, no arquivos dos diminutivos, a forma s.f.p já está sendo usada.

```
nouns/j-p.delaf.dict
15812pólio	pólio+N+F+SG
15813pólios	pólio+N+F+PL
15814pólio	pólio+N+M+SG
15815pólios	pólio+N+M+PL

diminutives/denominals.mbr.dict
227959polinho	pólio+N+DIM+F+SG
227960polinho	pólio+N+DIM+M+SG
227964polinhos	pólio+N+DIM+F+PL
227965polinhos	pólio+N+DIM+M+PL
228010poliozinha	pólio+N+DIM+F+SG
228011poliozinhas	pólio+N+DIM+F+PL
228012poliozinho	pólio+N+DIM+M+SG
228013poliozinhos	pólio+N+DIM+M+PL
```

2. para `expo` não tivemos muita dúvida, apenas eliminamos do recurso as entradas s.m. Embora os arquivos de diminutivos agora precisem ser regerados pelo @leoalenc 

```
diminutives/denominals.mbr.dict
123435expinho	expo+N+DIM+F+SG
123436expinho	expo+N+DIM+M+SG
123437expinhos	expo+N+DIM+F+PL
123438expinhos	expo+N+DIM+M+PL
123575expozinha	expo+N+DIM+F+SG
123576expozinhas	expo+N+DIM+F+PL
123577expozinho	expo+N+DIM+M+SG
123578expozinhos	expo+N+DIM+M+PL
```

3. O `ratio` é um pouco mais controverso. A forma s.f. vem do inglês. É um estrangeirismo. A forma s.m. vem do Latin, um estrangeirismo também? Os dois casos são iguais?  Qual critério de corte vamos adotar para inclusão de palavras estrangeiras neste recurso? Existem vários termos em Latin usados em domínios específicos como o Direito. Mas são usados literalmente, muitas vezes até com grafia destacada (itálico).  Vide comentários de:

1. http://www.portaldalinguaportuguesa.org/index.php?action=loanwords
2. https://pt.wikipedia.org/wiki/Estrangeirismo

Ficamos com as formas s.f e s.m e os diminutivos precisam ser ajustados.  

```
nouns/nouns.gfl.dict
77961ratio	ratio+N+F+SG
77962ratio	ratio+N+F+PL
77963ratio	ratio+N+M+SG
77964ratio	ratio+N+M+PL

diminutives/denominals.mbr.dict
242851ratinho	ratio+N+DIM+F+SG
242853ratinhos	ratio+N+DIM+F+PL
242859ratiozinha	ratio+N+DIM+F+SG
242860ratiozinhas	ratio+N+DIM+F+PL
```

@leoalenc seria bom termos um script que eu pudesse rodar quando modificar arquivos, fazendo commit apenas depois que todos os arquivos estejam consistentes. 

Respostas as perguntas que levanto aqui poderiam ser dadas no https://github.com/LFG-PTBR/MorphoBr/wiki, podemos criar uma seção lá com critério para manutenção do recurso.
